-- ==============================================================
-- VKM — full schema bootstrap for a fresh Supabase project
-- Paste this whole file into: Supabase Dashboard > SQL Editor > Run
-- Generated by concatenating supabase/migrations/*.sql in order.
-- ==============================================================


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- migration: 20260620020519_00cd3e35-624a-4b7b-824c-c122dca5f8d5.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- =========================
-- ENUM
-- =========================
CREATE TYPE public.app_role AS ENUM ('participant', 'coach', 'mentor', 'super_admin');

-- =========================
-- PROFILES
-- =========================
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_select_authenticated" ON public.profiles
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

-- =========================
-- USER ROLES
-- =========================
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

CREATE POLICY "user_roles_select_authenticated" ON public.user_roles
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "user_roles_admin_all" ON public.user_roles
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'))
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'));

-- =========================
-- PROGRAMS
-- =========================
CREATE TABLE public.programs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  duration_weeks INTEGER NOT NULL DEFAULT 16,
  status TEXT NOT NULL DEFAULT 'draft',
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.programs TO authenticated;
GRANT ALL ON public.programs TO service_role;
ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "programs_select_authenticated" ON public.programs
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "programs_modify_mentors_admins" ON public.programs
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'mentor') OR public.has_role(auth.uid(), 'super_admin'))
  WITH CHECK (public.has_role(auth.uid(), 'mentor') OR public.has_role(auth.uid(), 'super_admin'));

-- =========================
-- BATCHES
-- =========================
CREATE TABLE public.batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id UUID REFERENCES public.programs(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  start_date DATE,
  end_date DATE,
  capacity INTEGER,
  status TEXT NOT NULL DEFAULT 'upcoming',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.batches TO authenticated;
GRANT ALL ON public.batches TO service_role;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "batches_select_authenticated" ON public.batches
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "batches_modify_mentors_admins" ON public.batches
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'mentor') OR public.has_role(auth.uid(), 'super_admin'))
  WITH CHECK (public.has_role(auth.uid(), 'mentor') OR public.has_role(auth.uid(), 'super_admin'));

-- =========================
-- BATCH MEMBERS
-- =========================
CREATE TABLE public.batch_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id UUID NOT NULL REFERENCES public.batches(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL DEFAULT 'participant',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (batch_id, user_id, role)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.batch_members TO authenticated;
GRANT ALL ON public.batch_members TO service_role;
ALTER TABLE public.batch_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "batch_members_select_authenticated" ON public.batch_members
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "batch_members_modify_staff" ON public.batch_members
  FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'coach') OR
    public.has_role(auth.uid(), 'mentor') OR
    public.has_role(auth.uid(), 'super_admin')
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'coach') OR
    public.has_role(auth.uid(), 'mentor') OR
    public.has_role(auth.uid(), 'super_admin')
  );

-- =========================
-- UPDATED_AT helper
-- =========================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER programs_updated_at BEFORE UPDATE ON public.programs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER batches_updated_at BEFORE UPDATE ON public.batches
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================
-- AUTO-CREATE PROFILE + FIRST USER = SUPER_ADMIN
-- =========================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  has_admin BOOLEAN;
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url'
  );

  -- Existence check (not COUNT on auth.users). First user to ever get super_admin wins.
  -- Public signups after that are always participant. Use invites for staff roles.
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE role = 'super_admin' LIMIT 1)
  INTO has_admin;

  IF NOT has_admin THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'super_admin');
  ELSE
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'participant');
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- migration: 20260620020540_cdabdf51-b2cc-4d10-8a16-40ba5612ad63.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

REVOKE EXECUTE ON FUNCTION public.has_role(UUID, public.app_role) FROM anon, authenticated, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM anon, authenticated, PUBLIC;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- migration: 20260620024314_c4e1716e-9dda-4123-b185-7bdc82ce4a17.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
-- =========================================================
-- VKM PROGRAM DOMAIN
-- =========================================================

-- 1. PROGRAM WEEKS (16-week curriculum)
CREATE TABLE public.program_weeks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id UUID REFERENCES public.programs(id) ON DELETE CASCADE,
  week_no INTEGER NOT NULL CHECK (week_no BETWEEN 1 AND 52),
  phase TEXT NOT NULL,
  topic TEXT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('Online','Offline')),
  why TEXT NOT NULL,
  task TEXT NOT NULL,
  proof TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (program_id, week_no)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_weeks TO authenticated;
GRANT ALL ON public.program_weeks TO service_role;
ALTER TABLE public.program_weeks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "program_weeks_read_all" ON public.program_weeks
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "program_weeks_modify_staff" ON public.program_weeks
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'));

-- 2. MILESTONES
CREATE TABLE public.milestones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id UUID REFERENCES public.programs(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  unlock_week INTEGER NOT NULL,
  cost_inr INTEGER NOT NULL DEFAULT 0,
  reward_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  handover TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (program_id, code)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.milestones TO authenticated;
GRANT ALL ON public.milestones TO service_role;
ALTER TABLE public.milestones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "milestones_read_all" ON public.milestones
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "milestones_modify_staff" ON public.milestones
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'));

-- 3. BUSINESS BRAIN
CREATE TABLE public.business_brains (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  business_name TEXT,
  industry TEXT,
  location TEXT,
  years_running INTEGER,
  current_mrr_inr BIGINT,
  target_mrr_inr BIGINT,
  team_size INTEGER,
  top_products TEXT,
  lead_sources TEXT,
  monthly_leads INTEGER,
  closing_rate_pct NUMERIC(5,2),
  avg_deal_inr BIGINT,
  top_challenges TEXT,
  success_definition TEXT,
  ai_prompt TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.business_brains TO authenticated;
GRANT ALL ON public.business_brains TO service_role;
ALTER TABLE public.business_brains ENABLE ROW LEVEL SECURITY;
CREATE POLICY "brains_own_or_staff_select" ON public.business_brains
  FOR SELECT TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "brains_own_upsert" ON public.business_brains
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "brains_own_update" ON public.business_brains
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE TRIGGER business_brains_updated_at BEFORE UPDATE ON public.business_brains
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 4. WEEKLY PROGRESS
CREATE TABLE public.weekly_progress (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  batch_id UUID REFERENCES public.batches(id) ON DELETE SET NULL,
  week_no INTEGER NOT NULL CHECK (week_no BETWEEN 1 AND 52),
  attended BOOLEAN NOT NULL DEFAULT false,
  task_done BOOLEAN NOT NULL DEFAULT false,
  proof_url TEXT,
  proof_note TEXT,
  proof_status TEXT NOT NULL DEFAULT 'pending' CHECK (proof_status IN ('pending','approved','rejected')),
  coach_id UUID REFERENCES auth.users(id),
  reviewed_at TIMESTAMPTZ,
  points INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, week_no)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.weekly_progress TO authenticated;
GRANT ALL ON public.weekly_progress TO service_role;
ALTER TABLE public.weekly_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "wp_own_or_staff_select" ON public.weekly_progress
  FOR SELECT TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "wp_own_insert" ON public.weekly_progress
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "wp_own_update" ON public.weekly_progress
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (true);
CREATE TRIGGER weekly_progress_updated_at BEFORE UPDATE ON public.weekly_progress
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 5. MONTHLY RESULTS
CREATE TABLE public.monthly_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  batch_id UUID REFERENCES public.batches(id) ON DELETE SET NULL,
  month_no INTEGER NOT NULL CHECK (month_no BETWEEN 1 AND 12),
  revenue_up BOOLEAN NOT NULL DEFAULT false,
  leads_up BOOLEAN NOT NULL DEFAULT false,
  closing_up BOOLEAN NOT NULL DEFAULT false,
  bonus_points INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, month_no)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.monthly_results TO authenticated;
GRANT ALL ON public.monthly_results TO service_role;
ALTER TABLE public.monthly_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "mr_own_or_staff_select" ON public.monthly_results
  FOR SELECT TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "mr_staff_write" ON public.monthly_results
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'));

-- 6. POINTS LEDGER
CREATE TABLE public.points_ledger (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source TEXT NOT NULL CHECK (source IN ('attend','task','revenue','leads','closing','bonus','manual')),
  reference TEXT,
  points INTEGER NOT NULL,
  awarded_by UUID REFERENCES auth.users(id),
  awarded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.points_ledger TO authenticated;
GRANT ALL ON public.points_ledger TO service_role;
ALTER TABLE public.points_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY "pl_own_or_staff_select" ON public.points_ledger
  FOR SELECT TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "pl_staff_write" ON public.points_ledger
  FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'));

-- 7. MILESTONE AWARDS
CREATE TABLE public.milestone_awards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  milestone_code TEXT NOT NULL,
  awarded_by UUID REFERENCES auth.users(id),
  handover_mode TEXT,
  awarded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, milestone_code)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.milestone_awards TO authenticated;
GRANT ALL ON public.milestone_awards TO service_role;
ALTER TABLE public.milestone_awards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ma_own_or_staff_select" ON public.milestone_awards
  FOR SELECT TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "ma_staff_write" ON public.milestone_awards
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'));

-- 8. ONBOARDING TASKS
CREATE TABLE public.onboarding_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  step_no INTEGER NOT NULL CHECK (step_no BETWEEN 1 AND 7),
  owner TEXT NOT NULL,
  description TEXT NOT NULL,
  due_by TEXT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, step_no)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.onboarding_tasks TO authenticated;
GRANT ALL ON public.onboarding_tasks TO service_role;
ALTER TABLE public.onboarding_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ob_own_or_staff_select" ON public.onboarding_tasks
  FOR SELECT TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "ob_staff_write" ON public.onboarding_tasks
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'));

-- 9. COACH VISITS (offline weeks)
CREATE TABLE public.coach_visits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coach_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  participant_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_no INTEGER NOT NULL,
  visited_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.coach_visits TO authenticated;
GRANT ALL ON public.coach_visits TO service_role;
ALTER TABLE public.coach_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cv_own_or_staff" ON public.coach_visits
  FOR SELECT TO authenticated
  USING (coach_id = auth.uid()
    OR participant_id = auth.uid()
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "cv_staff_write" ON public.coach_visits
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (public.has_role(auth.uid(),'coach') OR public.has_role(auth.uid(),'mentor') OR public.has_role(auth.uid(),'super_admin'));

-- 10. AI ADVISOR THREADS
CREATE TABLE public.ai_advisor_threads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  prompt TEXT NOT NULL,
  response TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_advisor_threads TO authenticated;
GRANT ALL ON public.ai_advisor_threads TO service_role;
ALTER TABLE public.ai_advisor_threads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ait_own_select" ON public.ai_advisor_threads
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "ait_own_insert" ON public.ai_advisor_threads
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

-- =========================================================
-- HELPERS
-- =========================================================
CREATE OR REPLACE FUNCTION public.points_total(uid UUID)
RETURNS INTEGER LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(SUM(points), 0)::int FROM public.points_ledger WHERE user_id = uid;
$$;

CREATE OR REPLACE FUNCTION public.current_stage(uid UUID)
RETURNS TEXT LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT CASE
    WHEN public.points_total(uid) >= 1151 THEN 'Growth Champion'
    WHEN public.points_total(uid) >= 901  THEN 'Closer'
    WHEN public.points_total(uid) >= 601  THEN 'Operator'
    WHEN public.points_total(uid) >= 301  THEN 'Builder'
    ELSE 'Starter'
  END;
$$;

REVOKE EXECUTE ON FUNCTION public.points_total(UUID) FROM anon, authenticated, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.current_stage(UUID) FROM anon, authenticated, PUBLIC;
GRANT EXECUTE ON FUNCTION public.points_total(UUID) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.current_stage(UUID) TO authenticated, service_role;

-- =========================================================
-- SEED: default VK Mentorship program + curriculum + milestones + Batch 16
-- =========================================================
DO $$
DECLARE
  prog UUID;
BEGIN
  INSERT INTO public.programs (title, description, duration_weeks, status)
  VALUES (
    'VK Mentorship — 16-Week Transformation',
    '4 Months · 16 weekly sessions (every Tuesday). Foundation → Systems → Sell → Review. Investment ₹8,00,000. VK takes the weekly group class; Growth Coaches drive individual implementation.',
    16,
    'active'
  )
  RETURNING id INTO prog;

  INSERT INTO public.program_weeks (program_id, week_no, phase, topic, mode, why, task, proof) VALUES
    (prog, 1, 'Foundation','Lifestyle Changes + OMM','Online','Discipline & rhythm drive growth','Install morning routine + start daily OMM','OMM running 5+ days; routine log'),
    (prog, 2, 'Foundation','Business Goals','Online','Setting the right number & breaking it down','Set annual + monthly goal, cascade to team','Written goal sheet'),
    (prog, 3, 'Foundation','Team Aspiration + Goal Reveal','Offline','Aligning the whole team to one target','Run team aspiration + goal reveal session','Team goal board photo'),
    (prog, 4, 'Foundation','Role Clarity','Offline','Who owns what — KRA & KPI','Define KRA/KPI for every role','Signed role clarity chart'),
    (prog, 5, 'Systems','Culture & Values','Online','A culture that runs without you','Define 3-5 values + expected behaviours','Values document'),
    (prog, 6, 'Systems','GAM + Review-to-Act','Online','The review rhythm that compounds','Start monthly GAM + weekly review','First GAM minutes'),
    (prog, 7, 'Systems','CRM Implementation','Offline','Never lose a lead again','Set up CRM, import leads, define stages','CRM live with real leads'),
    (prog, 8, 'Systems','CRM + Automation (Uniklife SAS)','Offline','Automate the repetitive work','Automate follow-ups & tasks','2+ automations live'),
    (prog, 9, 'Sell','Branding, USP & 4M Message','Online','Why customers should choose you','Finalise USP + 4M message','USP + message doc'),
    (prog,10, 'Sell','Content + Video Engine','Online','Show up consistently','Plan + publish content/videos','1 week of content live'),
    (prog,11, 'Sell','Lead Generation + Marketing Review','Online','Turn on daily leads','Launch 1 lead source + weekly review','Leads coming in daily'),
    (prog,12, 'Sell','Sales STEPS + SCRIPTS','Online','A repeatable sales process','Build the sales steps + scripts','Script in use'),
    (prog,13, 'Sell','Objection Handling + Closing','Online','Convert more, discount less','Train objections + closing','Closing rate tracked'),
    (prog,14, 'Sell','Follow-up + Sales Team Training','Offline','No lead left behind','Follow-up system + team role-plays','Sales team trained'),
    (prog,15, 'Review','Final Review','Offline','What''s working, what to fix','Full systems + numbers review','Completed review scorecard'),
    (prog,16, 'Review','Graduation & Certificate','Offline','Celebrate & commit to the next level','Before-after + goal reveal + certificate','Before-after results');

  INSERT INTO public.milestones (program_id, code, name, unlock_week, cost_inr, reward_items, handover) VALUES
    (prog,'goal_setter','Goal Setter',3,2000,
      '["Branded CEO journal + premium pen","Framed ''My Growth Goal'' print","Welcome shout-out on socials"]'::jsonb,
      'In person on Week 3 offline visit, in front of the team'),
    (prog,'system_builder','System Builder',6,3000,
      '["Engraved ''System Builder'' desk trophy","VK Mentorship polo T-shirt","15-min 1:1 call with VK","''Win of the Week'' feature"]'::jsonb,
      'Announced live in the Tuesday class'),
    (prog,'growth_champion','Growth Champion',14,5000,
      '["Engraved ''Growth Champion'' crystal trophy","Leather Closer''s Kit folder","Gift hamper","Signed book","Success-story feature + reel"]'::jsonb,
      'In person on Week 14 offline visit, in front of the team');

  INSERT INTO public.batches (program_id, name, start_date, capacity, status)
  VALUES (prog, 'Batch 16', CURRENT_DATE, 15, 'active');
END $$;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- migration: 20260620024340_4c8ecee0-37fc-4a60-a3f6-db94e62df4f0.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
-- Tighten weekly_progress UPDATE WITH CHECK
DROP POLICY IF EXISTS "wp_own_update" ON public.weekly_progress;
CREATE POLICY "wp_own_update" ON public.weekly_progress
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'))
  WITH CHECK (user_id = auth.uid()
    OR public.has_role(auth.uid(),'coach')
    OR public.has_role(auth.uid(),'mentor')
    OR public.has_role(auth.uid(),'super_admin'));

-- Switch helpers to SECURITY INVOKER (RLS on points_ledger enforces access)
CREATE OR REPLACE FUNCTION public.points_total(uid UUID)
RETURNS INTEGER LANGUAGE SQL STABLE SECURITY INVOKER SET search_path = public AS $$
  SELECT COALESCE(SUM(points), 0)::int FROM public.points_ledger WHERE user_id = uid;
$$;

CREATE OR REPLACE FUNCTION public.current_stage(uid UUID)
RETURNS TEXT LANGUAGE SQL STABLE SECURITY INVOKER SET search_path = public AS $$
  SELECT CASE
    WHEN public.points_total(uid) >= 1151 THEN 'Growth Champion'
    WHEN public.points_total(uid) >= 901  THEN 'Closer'
    WHEN public.points_total(uid) >= 601  THEN 'Operator'
    WHEN public.points_total(uid) >= 301  THEN 'Builder'
    ELSE 'Starter'
  END;
$$;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- migration: 20260620030824_8c5e27a2-6cb6-4b0f-b510-9ac3f16fbff3.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- 1. profiles flag
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS must_reset_password boolean NOT NULL DEFAULT false;

-- 2. invites table
CREATE TABLE IF NOT EXISTS public.user_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  name text NOT NULL,
  role app_role NOT NULL,
  phone text,
  batch text,
  token text NOT NULL UNIQUE,
  temp_password text NOT NULL,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  accepted_at timestamptz,
  revoked_at timestamptz,
  accepted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  invited_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_invites_email_idx ON public.user_invites (lower(email));
CREATE INDEX IF NOT EXISTS user_invites_status_idx ON public.user_invites (status);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_invites TO authenticated;
GRANT SELECT ON public.user_invites TO anon;
GRANT ALL ON public.user_invites TO service_role;

ALTER TABLE public.user_invites ENABLE ROW LEVEL SECURITY;

-- Admin manage
CREATE POLICY "Admins manage invites"
  ON public.user_invites FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'))
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'));

-- Public read by token (for /invite/:token page) — restrict to non-revoked, non-expired
CREATE POLICY "Anyone can read pending invite to claim"
  ON public.user_invites FOR SELECT
  TO anon, authenticated
  USING (status = 'pending' AND revoked_at IS NULL AND expires_at > now());

-- Trigger updated_at
CREATE TRIGGER set_user_invites_updated_at
  BEFORE UPDATE ON public.user_invites
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 3. accept_invite function — called by signed-in user after they log in with temp password
CREATE OR REPLACE FUNCTION public.accept_invite_by_token(_token text)
RETURNS public.user_invites
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invite public.user_invites;
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT * INTO v_invite
  FROM public.user_invites
  WHERE token = _token
    AND status = 'pending'
    AND revoked_at IS NULL
    AND expires_at > now()
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invite not found, expired, or already used';
  END IF;

  UPDATE public.user_invites
  SET status = 'accepted',
      accepted_at = now(),
      accepted_by = v_uid
  WHERE id = v_invite.id
  RETURNING * INTO v_invite;

  -- Ensure role row exists
  INSERT INTO public.user_roles (user_id, role)
  VALUES (v_uid, v_invite.role)
  ON CONFLICT (user_id, role) DO NOTHING;

  -- Force reset on first login
  UPDATE public.profiles
  SET must_reset_password = true
  WHERE id = v_uid;

  RETURN v_invite;
END;
$$;

GRANT EXECUTE ON FUNCTION public.accept_invite_by_token(text) TO authenticated;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- migration: 20260620031556_64ed1319-8825-49b3-95c9-8700f08a05f3.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated, anon;

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- migration: 20260620040000_security_hardening_rls.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
-- =========================================================
-- SECURITY HARDENING — data-leakage & integrity fixes
-- =========================================================
-- Findings addressed:
--   CRITICAL: user_invites exposed token + temp_password to anon/authenticated
--   HIGH:     profiles leaked phone of every user to every authenticated user
--   MEDIUM:   weekly_progress let participants self-approve proofs / self-award points
--   MEDIUM:   user_roles readable by everyone (admin enumeration)
--   LOW:      has_role granted to anon (role-probing oracle)
-- =========================================================

-- ---------------------------------------------------------
-- CRITICAL 1: Lock down user_invites
-- The client never reads this table directly — all access goes through
-- service-role server functions (getInviteByToken, listInvites, etc.).
-- The anon/authenticated read policy leaked token + temp_password (plaintext).
-- ---------------------------------------------------------
DROP POLICY IF EXISTS "Anyone can read pending invite to claim" ON public.user_invites;
REVOKE SELECT ON public.user_invites FROM anon;
-- The remaining "Admins manage invites" policy (super_admin only) governs all
-- authenticated access — non-admins now match no policy row and see nothing.
-- Authenticated GRANTs are kept intact: the admin UI's revoke/list/resend server
-- functions act through the user-scoped client and rely on those grants + policy.

-- ---------------------------------------------------------
-- HIGH 2: Restrict profiles SELECT to self + staff
-- Protects phone numbers and any other PII from peer enumeration.
-- When public leaderboards need names/avatars, expose them through a
-- SECURITY DEFINER view that selects ONLY (id, full_name, avatar_url) —
-- never phone.
-- ---------------------------------------------------------
DROP POLICY IF EXISTS "profiles_select_authenticated" ON public.profiles;
CREATE POLICY "profiles_select_self_or_staff" ON public.profiles
  FOR SELECT TO authenticated
  USING (
    id = auth.uid()
    OR public.has_role(auth.uid(), 'coach')
    OR public.has_role(auth.uid(), 'mentor')
    OR public.has_role(auth.uid(), 'super_admin')
  );

-- ---------------------------------------------------------
-- MEDIUM 3: Restrict user_roles SELECT to self + admin
-- has_role() is SECURITY DEFINER, so role checks elsewhere are unaffected.
-- ---------------------------------------------------------
DROP POLICY IF EXISTS "user_roles_select_authenticated" ON public.user_roles;
CREATE POLICY "user_roles_select_self_or_admin" ON public.user_roles
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'super_admin'));

-- ---------------------------------------------------------
-- MEDIUM 4: weekly_progress integrity guard
-- RLS cannot restrict columns, so a participant editing their own row could set
-- proof_status='approved', points, coach_id, reviewed_at. Freeze those columns
-- for non-staff on both INSERT and UPDATE.
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.guard_weekly_progress()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  is_staff BOOLEAN := public.has_role(auth.uid(), 'coach')
    OR public.has_role(auth.uid(), 'mentor')
    OR public.has_role(auth.uid(), 'super_admin');
BEGIN
  IF is_staff THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    -- Participants may only create their own pending, unscored rows.
    NEW.proof_status := 'pending';
    NEW.points       := 0;
    NEW.coach_id     := NULL;
    NEW.reviewed_at  := NULL;
  ELSE
    -- Participants may update proof_url/proof_note/attended/task_done only;
    -- review-controlled columns retain their stored values.
    NEW.proof_status := OLD.proof_status;
    NEW.points       := OLD.points;
    NEW.coach_id     := OLD.coach_id;
    NEW.reviewed_at  := OLD.reviewed_at;
  END IF;

  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.guard_weekly_progress() FROM anon, authenticated, PUBLIC;

DROP TRIGGER IF EXISTS weekly_progress_guard ON public.weekly_progress;
CREATE TRIGGER weekly_progress_guard
  BEFORE INSERT OR UPDATE ON public.weekly_progress
  FOR EACH ROW EXECUTE FUNCTION public.guard_weekly_progress();

-- ---------------------------------------------------------
-- LOW 5: Remove the anon role-probing oracle
-- anon code paths use the service-role server client, not has_role().
-- ---------------------------------------------------------
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon;

