import type { Member } from "@/components/community/community-data";

// Sample members so the directory looks alive in demos. These are NOT real
// accounts — `mock: true` keeps them out of the real DM flow.
export type MockMember = Member & { bio: string };

export const MOCK_MEMBERS: MockMember[] = [
  {
    id: "00000000-0000-4000-8000-0000000000a1",
    name: "Anitha Rao",
    avatar: null,
    headline: "Founder · scaling a premium interior studio",
    businessName: "Anitha Designs",
    industry: "Interior Design",
    location: "Hyderabad",
    batchLabel: "Batch 15",
    status: "alumni",
    skills: ["Design", "Branding", "Client Sales"],
    allowMessages: true,
    mock: true,
    bio: "Built a 12-person interior studio from a 1-room office. Love talking systems, hiring, and turning referrals into a real pipeline.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a2",
    name: "Suresh Reddy",
    avatar: null,
    headline: "Wholesale distribution · 3 districts",
    businessName: "Sri Sai Traders",
    industry: "Distribution",
    location: "Vijayawada",
    batchLabel: "Batch 16",
    status: "active",
    skills: ["Operations", "Inventory", "Team"],
    allowMessages: true,
    mock: true,
    bio: "Distributing FMCG across 3 districts. Currently fixing my follow-up system and building a real sales team.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a3",
    name: "Lakshmi Nair",
    avatar: null,
    headline: "Retail apparel · 2 stores, going online",
    businessName: "Lakshmi Sarees",
    industry: "Retail / Apparel",
    location: "Kochi",
    batchLabel: "Batch 14",
    status: "alumni",
    skills: ["Retail", "Merchandising", "Instagram"],
    allowMessages: true,
    mock: true,
    bio: "Two saree stores and a growing online side. Happy to share what worked (and what didn't) launching D2C.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a4",
    name: "Ravi Teja",
    avatar: null,
    headline: "Civil contractor · residential projects",
    businessName: "Teja Constructions",
    industry: "Construction",
    location: "Hyderabad",
    batchLabel: "Batch 16",
    status: "active",
    skills: ["Project Mgmt", "Estimation", "Hiring"],
    allowMessages: true,
    mock: true,
    bio: "Residential construction. Working on role clarity and a GAM rhythm so projects stop depending only on me.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a5",
    name: "Imran Sheikh",
    avatar: null,
    headline: "Import / export · home décor",
    businessName: "Imran Imports",
    industry: "Import / Export",
    location: "Mumbai",
    batchLabel: "Batch 15",
    status: "alumni",
    skills: ["Sourcing", "Negotiation", "Logistics"],
    allowMessages: false,
    mock: true,
    bio: "Importing home décor from 4 countries. Ask me about supplier negotiation and cash-flow planning.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a6",
    name: "Priya Menon",
    avatar: null,
    headline: "Artisan bakery · wholesale + cafe",
    businessName: "Bloom Bakery",
    industry: "Food & Beverage",
    location: "Bangalore",
    batchLabel: "Batch 16",
    status: "active",
    skills: ["Branding", "Content", "Operations"],
    allowMessages: true,
    mock: true,
    bio: "Bakery with a cafe and a wholesale line. Obsessed with content and building a brand people remember.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a7",
    name: "Karthik Iyer",
    avatar: null,
    headline: "IT services · helping SMBs go digital",
    businessName: "Iyer Tech Solutions",
    industry: "IT Services",
    location: "Chennai",
    batchLabel: "Batch 14",
    status: "alumni",
    skills: ["CRM", "Automation", "Sales Process"],
    allowMessages: true,
    mock: true,
    bio: "We set up CRMs and automations for small businesses. Glad to help anyone implementing their CRM this batch.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a8",
    name: "Deepa Shetty",
    avatar: null,
    headline: "Wellness studios · 2 locations",
    businessName: "Shetty Wellness",
    industry: "Health & Wellness",
    location: "Mangalore",
    batchLabel: "Batch 16",
    status: "active",
    skills: ["Retention", "Memberships", "Team"],
    allowMessages: true,
    mock: true,
    bio: "Two wellness studios. Focused on memberships, retention, and finally building a leadership layer.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000a9",
    name: "Arjun Malhotra",
    avatar: null,
    headline: "Multi-brand auto workshop",
    businessName: "Malhotra Motors",
    industry: "Automotive",
    location: "Pune",
    batchLabel: "Batch 15",
    status: "alumni",
    skills: ["Service Ops", "Upselling", "Reviews"],
    allowMessages: true,
    mock: true,
    bio: "Multi-brand car service. Doubled revenue with a follow-up + review engine — happy to share the playbook.",
  },
  {
    id: "00000000-0000-4000-8000-0000000000b0",
    name: "Sneha Pillai",
    avatar: null,
    headline: "Boutique fashion label",
    businessName: "Pillai Boutique",
    industry: "Fashion Retail",
    location: "Trivandrum",
    batchLabel: "Batch 16",
    status: "active",
    skills: ["Design", "Paid Ads", "Influencers"],
    allowMessages: true,
    mock: true,
    bio: "Building a boutique fashion label. Learning paid ads and influencer collabs to drive consistent leads.",
  },
];

export const MOCK_BY_ID = new Map(MOCK_MEMBERS.map((m) => [m.id, m]));
